### ISSUE TITLE
Create an Incident by EC User

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#112]

**Comment by ManZzup** [comment]
@MrClemRkz  please advice @aijdissanayake on changes for the incident table

**Comment by aijdissanayake** [comment]
https://docs.google.com/document/d/1aXSGMvylehuBAh7Nb__JWDKHbGTukOxszPjf0jYb58s/edit#

**Comment by MrClemRkz** [comment]
## task breakdown
- [ ] incident info -> basic
- [ ] incident info -> advanced
- [ ] location info -> map view
- [ ] location info -> autoload select with related data
- [ ] contact info of complainer
- [ ] summary view

**Comment by ManZzup** [comment]
EC create incident is done
