### ISSUE TITLE
Create and Incident by a Civil User

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#38]
## User Story
AS A Civil user, I WANT to add and incident record to the system.

**Comment by ManZzup** [comment]
@MrClemRkz list the new additions for the civil user incident create view

**Comment by MrClemRkz** [comment]
We will have stepper view for the civil users.

but will need some changes in location as:
- Province, District, Polling Station and Police Station (rest will available on EC and Police views)
- need a way to let user pin-point the location (manually or by device location) 
-- could be a popup or new tab

Also need a way to upload files.

**Comment by MrClemRkz** [comment]
## task breakdown
- [ ] enable guest access (therefore no menu will be visible) (f)
- [ ] ref ID should be generated and shown at the submission of the form. (f+b)
- [ ] upon submission of form email should be sent with info of the incident.
- [ ] draft email template (probably html email)

**Comment by ManZzup** [comment]
Initial implementation completed.
Missing features to be added as Bugs/Feature requests
