### ISSUE TITLE
List Incident view with filters

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#39]
## User Story
AS A Complaint Coordinator, I WANT to list all incidents SO THAT I can confirm the completed ones to be processed further.

[incident-list-search]
![list_incidents_search](https://user-images.githubusercontent.com/16492984/60531903-a76a1000-9d19-11e9-8140-07717a88f1cd.png)

**Comment by ManZzup** [comment]
Things for the filtering 
- [ ] Search by ref ID
- [ ] Pagination
- [ ] Sort by last updated
- [ ] Drop downs - Severity, Status

**Comment by MrClemRkz** [comment]
## task breakdown - frontend
- [ ] action column
- [ ] response time due column

**Comment by ManZzup** [comment]
Fixed in https://github.com/ECLK/IncidentManagement/commit/0ca80c01b7b9e4597797af2a59ca618dfc17d437
