### ISSUE TITLE
Summary of incidents pending correspondence to complainers 

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#49]
## User Story
AS A Complaint Manager, I WANT to list all closed and not informed incidents SO THAT I can inform the complainers if their contactable information is given.

**Comment by ManZzup** [comment]
@MrClemRkz advice required

**Comment by MrClemRkz** [comment]
Well the idea is that **the resolution of an incident must be conveyed to the complainer.** (sometime we may need to send periodically or main updates as notifications to the complainer, so that he's informed that complaint is been processed.) 

Therefore we must have way to check that each complaint's resolution is sent back to complainer, via given reachable contact details. 

I also believe we must mention on the incident comment trail as both, 'tried and failed to reach' or 'message conveyed'. That being mentioned, **this will be an action set from incident review module**.

**Comment by MrClemRkz** [comment]
## task breakdown
- [ ] GET api to receive list of incidents which have not flagged as message conveyed to the complainer with pagination. (b)
- [ ] PUT / PATCH api to flagging up as message conveyed to the complainer. (b)
- [ ] list view for incident list which have not flagged as message conveyed to the complainer. (f)
- [ ] workflow to enforce a comment when flagging up as message conveyed to the complainer. (f)

**Comment by MrClemRkz** [comment]
This is changed and will be closed to avoid confusions.
